---
# Ansible Inventory - Generated by Terraform
# Do not edit manually

all:
  vars:
    ansible_user: ${ssh_user}
    ansible_ssh_private_key_file: ${ssh_private_key}
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  children:
    webservers:
      hosts:
%{ for idx, ip in web_servers ~}
        web${idx + 1}:
          ansible_host: ${ip}
%{ endfor ~}

    appservers:
      hosts:
%{ for idx, ip in app_servers ~}
        app${idx + 1}:
          ansible_host: ${ip}
%{ endfor ~}
